:toc: macro
:powershell-config: link:https://github.com/kboom/workspace-setup-windows-powershell[Workspace Setup Windows : PowerShell]
:git-extensions: link:https://github.com/gitextensions/gitextensions[Git Extensions]
:tomorrow-theme: link:https://github.com/chriskempson/tomorrow-theme[Tomorrow Theme]
:powershell-docs: link:PowerShell.adoc[PowerShell]
:mockoon: link:https://mockoon.com/[Mockoon]
:redux-devtools: link:https://microsoftedge.microsoft.com/addons/detail/redux-devtools/nnkgneoiohoecpdiaponcejilbhhikei[Redux Devtools]
:autohotkey: link:https://www.autohotkey.com/[Autohotkey]
:custom-curve: link:https://www.esreality.com/download.php?file_id=103413[CustomCurve]


= link:README.adoc[Home]

The list of tools that every developer might want to have installed.

---

toc::[]

---

== PowerShell

See {powershell-config} repository to set up your awesome PowerShell environment.

== Software

{git-extensions}::
Really nice UI for the git - close to Git Kraken but open source.

{mockoon}::
The best mocking server with and UI and CLI that you may wish for.

{autohotkey}::
In a simplest use case, it allows to remap the keys on your keyboard, but offers much more than that.
My own script for this is stored in this repository. Most importantly, it swaps left ctrl with left windows, so I'm using a thumb much more than a pinky finger (as in Mac), which is really great.
Just put the script in your startup directory located at `%appdata%\Microsoft\Windows\Start Menu\Programs\Startup`.

{custom-curve}::
A tiny utility which helps you modify your registry keys for your mouse, so that it goes faster than the limits. You also have much more control over how it behaves, useful for non-standard screen estate.
If you want your mouse to go beyond the speed limits offered in the control panel, that's the way to go - just scale it by the factor you like.

== React Application Development

{redux-devtools}::
A must-have for applications using Redux.

== Themes

My favourite theme is Gruvbox (for https://marketplace.visualstudio.com/items?itemName=jeffkelly.gruvboxvs10[Visual Studio])

== Windows tricks

1. Rather than trying to bring back the windows you were using after bringing up a different one just type alt + esc, as this will simply move the window to the bottom, but not minimize it, which is much more useful if the ones in front are not full size. This also works nicely with later alt + tab, if you need to bring back the window you just moved to back.
