:toc: macro
:oh-my-posh: https://ohmyposh.dev/[Oh My Posh]

= link:README.adoc[Home]

The list of tools that every developer might want to have installed.

---

toc::[]

---

== Set up

Customize your terminal::
Guide available here https://docs.microsoft.com/en-us/windows/terminal/install?WT.mc_id=-blog-scottha[here].
https://docs.microsoft.com/en-us/windows/terminal/tutorials/custom-prompt-setup[This] is the official Microsoft guide on how to enable oh-my-posh.
You should also go through this https://www.hanselman.com/blog/my-ultimate-powershell-prompt-with-oh-my-posh-and-the-windows-terminal[guide] if you want great glyphs.
You can customise your prompt further by changing the options in `ggurgul-oh-my-posh-profile.json` according to the https://ohmyposh.dev/docs/git[oh-my-posh docs].
You may also choose completely different theme from this[https://ohmyposh.dev/docs/themes] list.

== PowerShell

{oh-my-posh}::
Customise your shell profile.

== Windows tricks

1. Rather than trying to bring back the windows you were using after bringing up a different one just type alt + esc, as this will simply move the window to the bottom, but not minimize it, which is much more useful if the ones in front are not full size. This also works nicely with later alt + tab, if you need to bring back the window you just moved to back.
