:toc: macro

= Useful commands

This document present the most useful commands and techniques of PowerShell 7+.

---

toc::[]

---

== Setup

=== Customize your terminal

Guide available here https://docs.microsoft.com/en-us/windows/terminal/install?WT.mc_id=-blog-scottha[here].
https://docs.microsoft.com/en-us/windows/terminal/tutorials/custom-prompt-setup[This] is the official Microsoft guide on how to enable oh-my-posh.
You should also go through this https://www.hanselman.com/blog/my-ultimate-powershell-prompt-with-oh-my-posh-and-the-windows-terminal[guide] if you want great glyphs.
You can customise your prompt further by changing the options in `ggurgul-oh-my-posh-profile.json` according to the https://ohmyposh.dev/docs/git[oh-my-posh docs].
You may also choose completely different theme from https://ohmyposh.dev/docs/themes[this list].

You need to move or link the contents of this directory to your `$PROFILE` base directory.

=== Enable running scripts which you created locally
Run your terminal as administrator and issue `set-executionpolicy remotesigned` which will allow running ps1 scripts created locally but require the ones that you download to be signed. If you downloaded a script from the internet and you are sure it is secure then you can just right click on it and select "unblock". Make sure it is not read-only as otherwise it will fail with awkward error.

== Help

Try to find a command::
```
help *file*

Name                              Category  Module                    Synopsis
----                              --------  ------                    --------
New-ScriptFileInfo                Function  PowerShellGet             …
Test-ScriptFileInfo               Function  PowerShellGet             …
Update-ScriptFileInfo             Function  PowerShellGet             …
```

Try to find a command by noun::
```
get-command -noun file

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Out-File                                           7.0.0.0    Microsoft.PowerShell.Utility
Cmdlet          Unblock-File                                       7.0.0.0    Microsoft.PowerShell.Utility
```

See examples for a command::
`help hotfix -examples`

See details of the parameter::
`help get-help -parameter Name`

== Pipelines

Get members of a command::
```
Get-Service -Name w32time | Get-Member

   TypeName: System.Service.ServiceController#StartupType

Name                      MemberType    Definition
----                      ----------    ----------
Name                      AliasProperty Name = ServiceName
RequiredServices          AliasProperty RequiredServices = ServicesDependedOn
Disposed                  Event         System.EventHandler Disposed(System.Object, System.EventArgs)
Close                     Method        void Close()
Continue                  Method        void Continue()
Dispose                   Method        void Dispose(), void IDisposable.Dispose()
Equals                    Method        bool Equals(System.Object obj)
```

Select properties and sort by one of them::
```
Get-Process Spotify | Select-Object -Property Id, Name, CPU | Sort-Object -Descending -Property CPU

   Id Name            CPU
   -- ----            ---
10352 Spotify  7745.40625
29972 Spotify 2132.203125
33168 Spotify    685.1875
20580 Spotify    30.65625
27704 Spotify    0.296875
22796 Spotify     0.28125
```

== Loops

Simplest loop with action::
```
'1', '2' | ForEach-Object { Write-Host $_ }
```